application: ae-testapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest

handlers:
- url: /login
  script: main.app
  secure: always

- url: /admin
  script: main.app
  secure: always

- url: /.*
  script: main.app
  secure: never
